### ISSUE TITLE
unable to send logs to adx after update the plugin.

### ISSUE THREAD

**Issue by le0li9ht** [Azure/logstash-output-kusto#65]
I have upgraded the plugin to 2.0.2 with logstash 8.7.1 running. I am getting following error.
```
[2024-01-03T17:31:14,074][WARN ][io.netty.channel.AbstractChannelHandlerContext][main][8a0bb072871ccbb8b48dd50fdabd8fc3eba79d2bdd55af5e1ecdd48d9e47442a] An exception 'java.lang.NoSuchMethodError: 'int io.netty.util.internal.StringUtil.decodeHexNibble(byte)'' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NoSuchMethodError: 'int io.netty.util.internal.StringUtil.decodeHexNibble(byte)'
        at io.netty.handler.codec.http.HttpObjectDecoder.getChunkSize(HttpObjectDecoder.java:825) ~[netty-codec-http-4.1.94.Final.jar:4.1.94.Final]
        at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:384) ~[netty-codec-http-4.1.94.Final.jar:4.1.94.Final]
        at io.netty.handler.codec.http.HttpClientCodec$Decoder.decode(HttpClientCodec.java:239) ~[netty-codec-http-4.1.94.Final.jar:4.1.94.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373) [netty-handler-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236) [netty-handler-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285) [netty-handler-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) [netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) [netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) [netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.87.Final.jar:4.1.87.Final]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[2024-01-03T17:31:14,075][WARN ][reactor.netty.channel.FluxReceive][main][8a0bb072871ccbb8b48dd50fdabd8fc3eba79d2bdd55af5e1ecdd48d9e47442a] [94bf2272-1, L:/1:59746 - R:rceldtclient.queue.core.windows.net/IP:443] An exception has been observed post termination, use DEBUG level to see the full stack: java.lang.NoSuchMethodError: 'int io.netty.util.internal.StringUtil.decodeHexNibble(byte)'

```

**Comment by ag-ramachandran** [comment]
Hello @le0li9ht , While we look at this specific issue with 8.7.1, can you bump the version of logstash to say something > 8.7. We progressively fix CVEs on common libs and this causes issues in classpath in certain versions.

You can look at LS versions here : https://www.elastic.co/guide/en/logstash/current/releasenotes.html

**Comment by le0li9ht** [comment]
is there any way to downgrade the version. I can't do it via the logstash-plugin binary.

**Comment by ag-ramachandran** [comment]
Hello @le0li9ht 

To install an older version of the plugin use the logstash install command with --version flag (as specified in the help below)


Usage:
    bin/logstash-plugin install [OPTIONS] [PLUGIN] ...

Parameters:
    [PLUGIN] ...           plugin name(s) or file

Options:
    --version VERSION      version of the plugin to install
    --[no-]verify          verify plugin validity before installation (default: true)
    --preserve             preserve current gem options (default: false)
    --development          install all development dependencies of currently installed plugins (default: false)
    --local                force local-only plugin installation. see bin/logstash-plugin package|unpack (default: false)
    --[no-]conservative    do a conservative update of plugin's dependencies (default: true)
    -h, --help             print help

**Comment by ag-ramachandran** [comment]
@le0li9ht   Alternately you can dowload the specific version "gem" from release and use the -f option to install a specific version

**Comment by ag-ramachandran** [comment]
Hello @le0li9ht , If this worked, can we close this issue
